// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateUserAvatarReq is the update user avatar request.
 */
export interface UpdateUserAvatarReq {
    /**
     * new avatar URL
     */
    "avatar": string;
}

/**
 * UpdateUserNicknameReq is the update user nickname request.
 */
export interface UpdateUserNicknameReq {
    /**
     * new display name
     */
    "nickname": string | null;
}

/**
 * UserInfoResp is the user info response.
 */
export interface UserInfoResp {
    /**
     * user ID
     */
    "id": number;

    /**
     * username
     */
    "username": string;

    /**
     * display name
     */
    "nickname": string;

    /**
     * avatar URL
     */
    "avatar": string;

    /**
     * user status
     */
    "status": string;

    /**
     * creation time
     */
    "created_at": string;

    /**
     * last update time
     */
    "updated_at": string;
}
