// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UserService implements the user business operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetUserByID retrieves the user info by ID.
 */
export function GetUserByID(id: number): $CancellablePromise<$models.UserInfoResp | null> {
    return $Call.ByID(1714350307, id);
}

/**
 * UpdateUserAvatar updates the user avatar.
 */
export function UpdateUserAvatar(id: number, req: $models.UpdateUserAvatarReq | null): $CancellablePromise<$models.UserInfoResp | null> {
    return $Call.ByID(684477987, id, req);
}

/**
 * UpdateUserNickname updates the user nickname.
 */
export function UpdateUserNickname(id: number, req: $models.UpdateUserNicknameReq | null): $CancellablePromise<$models.UserInfoResp | null> {
    return $Call.ByID(1706801478, id, req);
}
