// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SetThemeReq is the set theme request.
 */
export interface SetThemeReq {
    /**
     * whether the web UI switched to dark mode
     */
    "dark": boolean;
}
