// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService implements the native window operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SetTheme repaints the native titlebar to match the web theme.
 * Custom colours only apply on Windows 11; older systems just switch dark mode.
 */
export function SetTheme(req: $models.SetThemeReq | null): $CancellablePromise<void> {
    return $Call.ByID(4153618025, req);
}
