// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Wexyuan/kairos"
	"github.com/Wexyuan/kairos/internal/config"
	"github.com/Wexyuan/kairos/internal/module/auth"
	"github.com/Wexyuan/kairos/internal/module/base"
	"github.com/Wexyuan/kairos/internal/module/desktop"
	"github.com/Wexyuan/kairos/internal/module/user"
	"github.com/Wexyuan/kairos/pkg/logger"
	"github.com/google/wire"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// Injectors from wire.go:

func NewWireApp(cfg *config.Config, log *logger.Logger) (*application.App, func(), error) {
	database, cleanup, err := provideDatabase(cfg, log)
	if err != nil {
		return nil, nil, err
	}
	snowflake, err := provideSnowflake(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache, cleanup2, err := provideCache(cfg, log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := base.NewRepository(database, snowflake, cache)
	userRepository := user.NewUserRepository(repository)
	userService := user.NewUserService(userRepository)
	authRepository := auth.NewAuthRepository(repository)
	tokenManager, err := provideTokenManager(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authService := auth.NewAuthService(userRepository, authRepository, tokenManager)
	windowService := desktop.NewWindowService()
	app := NewApp(userService, authService, windowService)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// InfraProviderSet defines the infrastructure providers.
var InfraProviderSet = wire.NewSet(
	provideDatabase,
	provideSnowflake,
	provideCache,
	provideTokenManager,
)

// ModuleProviderSet defines the business module providers.
var ModuleProviderSet = wire.NewSet(base.NewRepository, user.NewUserRepository, user.NewUserService, auth.NewAuthRepository, auth.NewAuthService, desktop.NewWindowService)

func NewApp(
	userSvc *user.UserService,
	authSvc *auth.AuthService,
	winSvc *desktop.WindowService,
) *application.App {
	return application.New(application.Options{
		Name:     "kairos",
		Services: []application.Service{application.NewService(userSvc), application.NewService(authSvc), application.NewService(winSvc)},
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(kairos.Assets),
		},
	},
	)
}
