// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Wexyuan/kairos/internal/config"
	"github.com/Wexyuan/kairos/internal/module/auth"
	"github.com/Wexyuan/kairos/internal/module/base"
	"github.com/Wexyuan/kairos/internal/module/user"
	"github.com/Wexyuan/kairos/internal/router"
	"github.com/Wexyuan/kairos/internal/server"
	"github.com/Wexyuan/kairos/pkg/app"
	"github.com/Wexyuan/kairos/pkg/logger"
	server2 "github.com/Wexyuan/kairos/pkg/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWireApp(cfg *config.Config, log *logger.Logger) (*app.App, func(), error) {
	tokenManager, err := provideTokenManager(cfg)
	if err != nil {
		return nil, nil, err
	}
	handlerFunc := provideAuthRequired(tokenManager)
	handler := base.NewHandler(log)
	database, cleanup, err := provideDatabase(cfg, log)
	if err != nil {
		return nil, nil, err
	}
	snowflake, err := provideSnowflake(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache, cleanup2, err := provideCache(cfg, log)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := base.NewRepository(database, snowflake, cache)
	service := base.NewService(log, repository)
	userRepository := user.NewUserRepository(repository)
	authRepository := auth.NewAuthRepository(repository)
	authService := auth.NewAuthService(service, userRepository, authRepository, tokenManager)
	authHandler := auth.NewAuthHandler(handler, authService)
	userService := user.NewUserService(service, userRepository)
	userHandler := user.NewUserHandler(handler, userService)
	routerRouter := router.New(log, cfg, handlerFunc, authHandler, userHandler)
	httpServer := server.NewHTTPServer(cfg, routerRouter)
	appApp := NewApp(cfg, httpServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// InfraProviderSet defines the infrastructure providers.
var InfraProviderSet = wire.NewSet(
	provideDatabase,
	provideSnowflake,
	provideCache,
	provideTokenManager,
)

// ModuleProviderSet defines the business module providers.
var ModuleProviderSet = wire.NewSet(base.NewRepository, base.NewService, base.NewHandler, user.NewUserRepository, user.NewUserService, user.NewUserHandler, auth.NewAuthRepository, auth.NewAuthService, auth.NewAuthHandler)

// MiddlewareProviderSet defines the middleware providers.
var MiddlewareProviderSet = wire.NewSet(
	provideAuthRequired,
)

// RouterProviderSet defines the router providers.
var RouterProviderSet = wire.NewSet(router.New)

// ServerProviderSet defines the server providers.
var ServerProviderSet = wire.NewSet(server.NewHTTPServer)

func NewApp(cfg *config.Config, httpServer *server2.HTTPServer) *app.App {
	return app.NewApp(app.WithName(cfg.App.Name), app.WithServers(httpServer))
}
