// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService implements the authentication business operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as user$0 from "../user/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangeUserPassword changes the user password.
 */
export function ChangeUserPassword(userID: number, req: $models.ChangeUserPasswordReq | null): $CancellablePromise<void> {
    return $Call.ByID(1546371872, userID, req);
}

/**
 * Login authenticates the user.
 */
export function Login(req: $models.LoginReq | null): $CancellablePromise<$models.TokenInfoResp | null> {
    return $Call.ByID(391036155, req);
}

/**
 * Logout logs out the user.
 */
export function Logout(userID: number): $CancellablePromise<void> {
    return $Call.ByID(1579482664, userID);
}

/**
 * Refresh refreshes the token pair.
 */
export function Refresh(req: $models.RefreshReq | null): $CancellablePromise<$models.TokenInfoResp | null> {
    return $Call.ByID(3933564277, req);
}

/**
 * Register registers a user.
 */
export function Register(req: $models.RegisterReq | null): $CancellablePromise<user$0.UserInfoResp | null> {
    return $Call.ByID(4265289575, req);
}
