// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChangeUserPasswordReq is the change user password request.
 */
export interface ChangeUserPasswordReq {
    /**
     * old password
     */
    "old_password": string;

    /**
     * new password
     */
    "new_password": string;
}

/**
 * LoginReq is the login request.
 */
export interface LoginReq {
    /**
     * username
     */
    "username": string;

    /**
     * plain password
     */
    "password": string;
}

/**
 * RefreshReq is the refresh token request.
 */
export interface RefreshReq {
    /**
     * plain refresh token
     */
    "refresh_token": string;
}

/**
 * RegisterReq is the register request.
 */
export interface RegisterReq {
    /**
     * unique username
     */
    "username": string;

    /**
     * plain password
     */
    "password": string;
}

/**
 * TokenInfoResp is the token pair response.
 */
export interface TokenInfoResp {
    /**
     * access token
     */
    "access_token": string;

    /**
     * refresh token
     */
    "refresh_token": string;

    /**
     * access token lifetime in seconds
     */
    "expires_in": number;
}
